#########################
### build environment ###
#########################

# base image - latest LTS
FROM node:dubnium as builder

# install chrome for protractor tests
# RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
# RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
# RUN apt-get update && apt-get install -yq google-chrome-stable

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# angular cli
RUN npm install -g @angular/cli@7.0.3 --unsafe

# install and cache app dependencies
COPY package.json package.json
RUN npm install --silent

# add app
COPY . .

# run tests
# RUN ng test --watch=false

# generate build
RUN npm run build

##################
### production ###
##################

FROM nginx:1.15.1-alpine

# copy artifact build from the 'build environment' above
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

# run nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
