/**
 * BC Gov News API Service 1.0
 * News API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DataIndex } from './dataIndex';


export interface Category extends DataIndex {
    twitterFeedUsername?: string;
    flickrUri?: string;
    youtubeUri?: string;
    audioUri?: string;
    isActive?: boolean;
    name?: string;
    topPostKey?: string;
    featurePostKey?: string;
}
