/**
 * BC Gov News API Service 1.0
 * News API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DocumentContact } from './documentContact';


export interface Document {
    pageTitle?: string;
    languageId?: number;
    headline?: string;
    subheadline?: string;
    detailsHtml?: string;
    byline?: string;
    contacts?: Array<DocumentContact>;
}
