/**
 * BC Gov News API Service 1.0
 * News API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Contact } from './contact';
import { ResourceLink } from './resourceLink';


export interface Ministry extends Category {
    childMinistryKey?: string;
    parentMinistryKey?: string;
    ministryUrl?: string;
    displayAdditionalName?: string;
    topicLinks?: Array<ResourceLink>;
    serviceLinks?: Array<ResourceLink>;
    newsletterLinks?: Array<ResourceLink>;
    ministerName?: string;
    contactUser?: Contact;
    secondContactUser?: Contact;
    weekendContactNumber?: string;
    twitterFeedUsername?: string;
    flickrUri?: string;
    youtubeUri?: string;
    audioUri?: string;
    isActive?: boolean;
    name?: string;
    topPostKey?: string;
    featurePostKey?: string;
}
