/**
 * BC Gov Hub API service
 * The .Net Core API for the Hub
 *
 * OpenAPI spec version: Alpha
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Activity {
    id?: number;
    startDateTime?: Date;
    endDateTime?: Date;
    potentialDates?: string;
    title?: string;
    details: string;
    hqComments?: string;
    schedule: string;
    significance: string;
    strategy?: string;
    comments?: string;
    leadOrganization?: string;
    contactMinistryAbbreviation?: string;
    venue?: string;
    cityName?: string;
    otherCity?: string;
    isActive?: boolean;
    isConfirmed?: boolean;
    isIssue?: boolean;
    isAllDay?: boolean;
    nrDateTime?: Date;
    lastUpdatedDateTime?: Date;
    categories?: Array<string>;
    ministriesSharedWith?: Array<string>;
}
