/**
 * BC Gov Hub API service
 * The .Net Core API for the Hub
 *
 * OpenAPI spec version: Alpha
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DocumentContact } from './documentContact';


export interface Document { 
    pageTitle?: string;
    languageId?: number;
    headline?: string;
    subheadline?: string;
    bodyHtml?: string;
    byline?: string;
    contacts?: Array<DocumentContact>;
}
