/**
 * BC Gov Hub API service
 * The .Net Core API for the Hub
 *
 * OpenAPI spec version: Alpha
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Message { 
    id?: string;
    title: string;
    description?: string;
    sortOrder?: number;
    isHighlighted?: boolean;
    isPublished?: boolean;
    timestamp?: Date;
}
