/**
 * BC Gov Hub API service
 * The .Net Core API for the Hub
 *
 * OpenAPI spec version: Alpha
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Ministry { 
    id?: string;
    key?: string;
    sortOrder?: number;
    displayName?: string;
    abbreviation?: string;
    isActive?: boolean;
    ministerEmail?: string;
    ministerPhotoUrl?: string;
    ministerPageHtml?: string;
    timestamp?: Date;
    miscHtml?: string;
    miscRightHtml?: string;
    twitterUsername?: string;
    flickrUrl?: string;
    youtubeUrl?: string;
    audioUrl?: string;
    facebookEmbedHtml?: string;
    youtubeEmbedHtml?: string;
    audioEmbedHtml?: string;
    topReleaseId?: string;
    featureReleaseId?: string;
    ministerAddress?: string;
    ministerName?: string;
    ministerSummary?: string;
    parentId?: string;
    ministryUrl?: string;
    contactUserId?: number;
    secondContactUserId?: number;
    weekendContactNumber?: string;
    eodFinalizedDateTime?: Date;
    eodLastRunUserId?: number;
    eodLastRunDateTime?: Date;
    displayAdditionalName?: string;
}
