/**
 * BC Gov Hub API service
 * The .Net Core API for the Hub
 *
 * OpenAPI spec version: Alpha
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Document } from './document';


export interface Post { 
    kind?: string;
    timestamp?: Date;
    key: string;
    reference?: string;
    summary?: string;
    location?: string;
    leadMinistryKey?: string;
    leadMinistryName?: string;
    ministryKeys?: Array<string>;
    ministries?: Array<string>;
    publishDateTime?: Date;
    isCommitted?: boolean;
    assetUrl?: string;
    documents?: Array<Document>;
}
