apiVersion: v1
kind: Template
metadata:
  name: "${NAME}-sonar-build-template"
  creationTimestamp:
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
  spec:
    triggers:
    - type: ImageChange
    - type: ConfigChange
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: "${GIT_REPO_URL}"
        ref: "${GIT_REF}"
      contextDir: "${SOURCE_CONTEXT_DIR}"
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: "${SOURCE_IMAGE_KIND}"
          name: "${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}"
        env:
        - name: SONAR_TOKEN
          value: "${SONAR_TOKEN}"
        - name: SONAR_PROJECT_KEY
          value: "${SONAR_PROJECT_KEY}"
        - name: SONAR_URL
          value: "${SONAR_URL}"
        - name: SONAR_PROJECT
          value: "${SONAR_PROJECT}"
    resources:
      requests:
        cpu: "${CPU_REQUEST}"
        memory: "${MEMORY_REQUEST}"
      limits:
        cpu: "${CPU_LIMIT}"
        memory: "${MEMORY_LIMIT}"
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: news-dashboard-develop
- name: GIT_REPO_URL
  displayName: Git Repo URL
  description: The URL to your GIT repo.
  required: true
  value: https://github.com/bcgov/gcpe-news-dashboard.git
- name: GIT_REF
  displayName: Git Reference
  description: The git reference or branch.
  required: true
  value: develop
- name: SOURCE_CONTEXT_DIR
  displayName: Source Context Directory
  description: The source context directory.
  required: false
  value: ''
- name: SOURCE_IMAGE_KIND
  displayName: Source Image Kind
  description: The 'kind' (type) of the  source image; typically ImageStreamTag, or
    DockerImage.
  required: true
  value: ImageStreamTag
- name: SOURCE_IMAGE_NAME
  displayName: Source Image Name
  description: The name of the source image.
  required: true
  value: frontend-yarn-builder-sonar
- name: SOURCE_IMAGE_TAG
  displayName: Source Image Tag
  description: The tag of the source image.
  required: true
  value: latest
- name: OUTPUT_IMAGE_TAG
  displayName: Output Image Tag
  description: The tag given to the built image.
  required: true
  value: latest
- name: CPU_LIMIT
  displayName: Resources CPU Limit
  description: The resources CPU limit (in cores) for this build.
  required: true
  value: '1'
- name: MEMORY_LIMIT
  displayName: Resources Memory Limit
  description: The resources Memory limit (in Mi, Gi, etc) for this build.
  required: true
  value: 6Gi
- name: CPU_REQUEST
  displayName: Resources CPU Request
  description: The resources CPU request (in cores) for this build.
  required: true
  value: '1'
- name: MEMORY_REQUEST
  displayName: Resources Memory Request
  description: The resources Memory request (in Mi, Gi, etc) for this build.
  required: true
  value: 4Gi
- name: SONAR_TOKEN
  displayName: Sonarqube Token
  description: The SonarQube user token
  required: true
  value: '123'
- name: SONAR_URL
  displayName: SonarQube URL
  description: The SonarQube URL
  required: true
  value: 'https://sonarqube-05e933-tools.pathfinder.gov.bc.ca'
- name: SONAR_PROJECT_KEY
  displayName: SonarQube Project Key
  description: The SonarQube project to add data to
  required: true
  value: News-Dashboard-Develop
- name: SONAR_PROJECT
  displayName: SonarQube Project Key
  description: The SonarQube project to add data to
  required: true
  value: News-Dashboard-Develop
