kind: Template
apiVersion: v1
metadata:
  name: "${NAME}"
  creationTimestamp: null
  annotations:
    tags: "builder,nodejs,yarn"
    iconClass: icon-nodejs
    description: >-
      This template defines resources needed to build Angular frontend
      applications. This is your builder image that compiles the Angular source
      code. This builder image uses YARN instead of NPM to build the frontend.
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${NAME}"
      annotations:
        description: Keeps track of changes in this builder image.
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${NAME}"
      creationTimestamp: null
      annotations:
        description: Defines how to build Angular applications from source code.
    spec:
      runPolicy: Serial
      triggers:
        - type: ConfigChange
      source:
        type: Git
        git:
          ref: "${GIT_REF}"
          uri: "${GIT_REPO_URL}"
        contextDir: "${SOURCE_CONTEXT_DIR}"
      strategy:
        type: Docker
        sourceStrategy:
          env:
          - name: SONAR_URL
            value: "${SONAR_URL}"
          - name: SONAR_TOKEN
            value: "${SONAR_TOKEN}"
          - name: SONAR_PROJECT
            value: "${SONAR_PROJECT}"
      output:
        to:
          kind: ImageStreamTag
          name: "${BUILDER_IMAGE_NAME}:latest"
    resources:
      requests:
        cpu: "${CPU_REQUEST}"
        memory: "${MEMORY_REQUEST}"
      limits:
        cpu: "${CPU_LIMIT}"
        memory: "${MEMORY_LIMIT}"
      postCommit: {}
    status:
      lastVersion: 0
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: News-Dashboard
- name: GIT_REPO_URL
  displayName: Git Repo URL
  description: The URL to your GIT repo.
  required: true
  value: https://github.com/bcgov/gcpe-news-dashboard.git
- name: GIT_REF
  displayName: Git Reference
  description: The git reference or branch.
  required: true
  value: master
- name: SOURCE_CONTEXT_DIR
  displayName: Source Context Directory
  description: The source context directory.
  required: false
  value: ''
- name: BUILDER_IMAGE_NAME
  displayName: Builder Image
  description:
    The name assigned to the builder image defined in this template. You
    should keep this as default unless you know what you are doing.
  required: true
  value: news-dashboard-sonar
- name: CPU_LIMIT
  displayName: Resources CPU Limit
  description: The resources CPU limit (in cores) for this build.
  required: true
  value: '1'
- name: MEMORY_LIMIT
  displayName: Resources Memory Limit
  description: The resources Memory limit (in Mi, Gi, etc) for this build.
  required: true
  value: 6Gi
- name: CPU_REQUEST
  displayName: Resources CPU Request
  description: The resources CPU request (in cores) for this build.
  required: true
  value: '1'
- name: MEMORY_REQUEST
  displayName: Resources Memory Request
  description: The resources Memory request (in Mi, Gi, etc) for this build.
  required: true
  value: 4Gi
- name: SONAR_TOKEN
  displayName: Sonarqube Token
  description: The SonarQube user token
  required: true
  value: '123'
- name: SONAR_URL
  displayName: SonarQube URL
  description: The SonarQube URL
  required: true
  value: 'https://sonarqube-ntu9uh-tools.pathfinder.gov.bc.ca'
- name: SONAR_PROJECT
  displayName: SonarQube Project Name
  description: The SonarQube Project Name
  required: true
  value: News-Dashboard-Master

